class QueueConfig:
    MAX_CONCURRENT_QUEUE_TASKS: int = 1

    SEMAPHORE_VALUE: int = MAX_CONCURRENT_QUEUE_TASKS
    NUM_WORKERS_QUEUE: int = MAX_CONCURRENT_QUEUE_TASKS
    MAX_WORKERS_POOL: int = MAX_CONCURRENT_QUEUE_TASKS
